[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build", "chmod +x start.sh"]

[start]
# TODO: Quitar db:reset del start.sh despu√©s del primer deploy exitoso
cmd = "./start.sh"

[variables]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "80"
