[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install --no-save"]

[phases.build]
cmds = ["bun run build"]

[start]
# TODO: Quitar db:reset de src/db/start.ts despu√©s del primer deploy exitoso
cmd = "bun src/db/start.ts"

[variables]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "80"
