[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
# TODO: Quitar db:reset despu√©s del primer deploy exitoso
cmd = "bun src/db/reset.ts && bun src/db/up.ts && bun src/db/seed.ts && bun dist/server/entry.mjs"

[variables]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "80"
